### ISSUE TITLE
Task list formatting

### ISSUE THREAD

**Issue by mntn-xyz** [tdemin/gmnhg#14]
These should probably be formatted as regular lists, right now they are collapsed into a single line.

Markdown:
```
Example task list
- [x] Theme website
- [x] Write formatting test page
- [ ] Fix the bugs
```

Output:
```
Example task list - [x] Theme website - [x] Write formatting test page - [ ] Fix the bugs
```

**Comment by tdemin** [comment]
@mntn-xyz they are? They seem to work just fine in the current master:

![Task list test](https://user-images.githubusercontent.com/26599554/130364294-749d156c-2025-47f4-8dc0-ebbaf0f33533.png)
![Task list test with completed items](https://user-images.githubusercontent.com/26599554/130364329-66708598-f846-4d5b-bbc6-8ae09835e0a1.png)

**Comment by mntn-xyz** [comment]
Hmm, maybe it's just the lack of extra newline between the text "Example task list" and the actual list? That's allowed for lists in CommonMark but I am not sure what standard Hugo uses.

**Comment by tdemin** [comment]
@mntn-xyz it might sure be. Hugo uses Goldmark which is CommonMark-compliant, but can be configured (and used) to use Blackfriday, which is what gomarkdown descended from.

In this case gomarkdown (combined with a few `fmt.Printf("%T: %+v:")`) seems to not detect a list there at all if I remove the newline.

**Comment by mntn-xyz** [comment]
Ah ok, it looks like this is controlled by a gomarkdown extension, "NoEmptyLineBeforeBlock". Are you aware of any reason not to enable this? I think it originates from a similar flag in blackfriday (EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK).

https://pkg.go.dev/github.com/gomarkdown/markdown/parser?utm_source=godoc#Extensions

**Comment by tdemin** [comment]
@mntn-xyz not really, and I'll probably enable that now.

Funnily enough, this is already a breaking change, but we aren't forced to do anything specific because of this at v0, and most people would probably expect it to work like it is. This should probably be configurable, but at this time this requires a large uplift of either adding another configuration file independent of Hugo (which kinda defeats the point of gmnhg playing mostly the same rules as Hugo), or trying to keep up with Hugo's various ways to configure a site (which change from time to time).

**Comment by tdemin** [comment]
@mntn-xyz works for you at master?

**Comment by mntn-xyz** [comment]
Confirmed, thanks for the fix.
