### ISSUE TITLE
Blockquotes

### ISSUE THREAD

**Issue by mntn-xyz** [tdemin/gmnhg#5]
Just wanted to note a couple of issues:

- Multiline blockquotes don't render properly; renderer should be able to handle line breaks and blank quoted lines
- HTML tags in blockquotes are not stripped (the typical Hugo markdown example page uses `<br>` and `<cite>` which are present in the output)

**Comment by tdemin** [comment]
@mntn-xyz first of all, sorry for taking that much of a while to respond, the last few days were quite a time. :-D

Removing line breaks in blockquotes is an intended behaviour, as there's no line length limit in Gemtext documents, and Gemini spec strongly recommends allowing clients to soft wrap text; therefore text in blockquotes is treated the same way general text is; see `internal/gemini/renderer.go#L91` (it calls `(Renderer).text()`, which strips line breaks). To be honest, I see no good way to keep author's line breaks in text while staying compatible with the Gemtext soft wrapping premise; do you?

Blank quotes are indeed an issue and do cause a panic, thanks to the (faulty) logic of `(Renderer).blockquote()` always expecting at least a single paragraph. While checking this I also discovered an apparent issue of more than one blockquote being merged by gomarkdown into one and then the rest of blockquotes getting ignored (I honestly didn't think of more than one paragraph in a single blockquote, hence the logic of `(Renderer).blockquote()` and the bug).

HTML tags in blockquotes being kept appears to be a gomarkdown issue, because the logic for paragraph/blockquote text extraction. I'll probably open a separate issue for this one and investigate if it's actually upstream causing this.

![md2gmn blockquote test](https://user-images.githubusercontent.com/26599554/129233185-e2bf6225-bb6b-47be-9957-adec78c351f7.png)

**Comment by mntn-xyz** [comment]
No problem, thanks for getting back to me! I'm just glad you're maintaining this, I think it will be useful for spreading Gemini adoption.

So on line breaks, it is true that the Gemini spec says that "quoted content is written as a single line". But it doesn't say that you can't put one quote right after another, and generally blockquotes are often used to output more than one line or paragraph.

To me, the most obvious use cases for multiline blockquotes are multi-paragraph quotes and poetry. You can find some examples here: gemini://whither.smol.pub/quotes. Some clients render these as multiline blockquotes (with wrapping!) while some simply display them as plain text lines. Currently the vulpes.one proxy just wraps each line, and it looks funny but it's technically in spec: https://proxy.vulpes.one/gemini/whither.smol.pub/quotes

In fact it isn't required for Gemini clients to render these lines any differently than normal text: "It is strictly optional for clients to do anything special at all with blockquotes, and some clients will treat them just like any other line of text." Since lines of text support newlines (they are inserted verbatim), it follows that newlines should be supported here as well.

For what it's worth, I think this should be clarified in the official Gemini spec.

**Comment by tdemin** [comment]
@mntn-xyz looks good to you?

![](https://user-images.githubusercontent.com/26599554/129306517-0a4d9520-d821-4fd9-9659-247d2cd95fc1.png)

**Comment by mntn-xyz** [comment]
I would consider that fixed!
